### ISSUE TITLE
教えてください

### ISSUE THREAD

**Issue by C0B21017** [takaemonn/ProjExD#2]
https://github.com/takaemonn/ProjExD/blob/5fbdcfd81dba0550a91378be797cc57d58fa99d1/ex01/alphabet.py#L13
sorted することでどうなっているのですか？

**Comment by takaemonn** [comment]
ソートされた文字列の1文字ずつを要素として、リストに格納しています。詳しくはhttps://note.nkmk.me/python-list-sort-sorted/ で確認ください
