### ISSUE TITLE
変数

### ISSUE THREAD

**Issue by c0b21027** [takaemonn/ProjExD#3]
ここと”ro"の部分で、別に変数定義する必要ないと思います。
https://github.com/takaemonn/ProjExD/blob/06b687070b54ec26e8391f9fce37022d0faf9acc/ex02/calc.py#L73

**Comment by takaemonn** [comment]
ありがとうございます。73行目の変数定義は1～9の数字を3×3の形に表示するために、89行目の変数定義は-, *, / を縦一列に表示するために必要と考えます。今回はこの部分の修正をしないこととします。
